name: my_jobs
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies: # NÂO MEXER NAS DEPENDENCIAS POR FAVOR!
  flutter:
    sdk: flutter
  vector_math: ^2.1.4
  flutter_svg: ^2.1.0
  equatable: ^2.0.3
  lottie: ^1.2.2
  bloc: ^8.0.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  webview_flutter: ^4.2.1
  webview_flutter_android: ^3.10.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  pusher_channels_flutter: ^2.1.2
  flutter_chat_ui: ^1.6.6
  flutter_chat_types: ^3.6.0
  uuid: ^4.3.3

  # flutter_web_auth: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    # - lib/assets/images/
    - assets/animation/init.json
    - assets/images/modal.png
    - assets/images/logo.svg
    - assets/images/mala_logo.svg
