// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fqVOwUmUC3QBxPAwDmOKtzAlJsnJMyk',
    appId: '1:1000499954052:web:71230659baca4e414fddd1',
    messagingSenderId: '1000499954052',
    projectId: 'studentsjob-d9128',
    authDomain: 'studentsjob-d9128.firebaseapp.com',
    storageBucket: 'studentsjob-d9128.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfPfJBsvCOy2h71IrWmMqCmr-3ry_MjFw',
    appId: '1:1000499954052:android:4570fbaed6b4a9b74fddd1',
    messagingSenderId: '1000499954052',
    projectId: 'studentsjob-d9128',
    storageBucket: 'studentsjob-d9128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkQY6LJJa_jGiSXNXrqNNypmFYHuqdiQk',
    appId: '1:1000499954052:ios:37b0643cfd719eb14fddd1',
    messagingSenderId: '1000499954052',
    projectId: 'studentsjob-d9128',
    storageBucket: 'studentsjob-d9128.firebasestorage.app',
    iosClientId: '1000499954052-70hemko3djtfuodcmijj2a062db8ks3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myJobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkQY6LJJa_jGiSXNXrqNNypmFYHuqdiQk',
    appId: '1:1000499954052:ios:37b0643cfd719eb14fddd1',
    messagingSenderId: '1000499954052',
    projectId: 'studentsjob-d9128',
    storageBucket: 'studentsjob-d9128.firebasestorage.app',
    iosClientId: '1000499954052-70hemko3djtfuodcmijj2a062db8ks3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myJobs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_fqVOwUmUC3QBxPAwDmOKtzAlJsnJMyk',
    appId: '1:1000499954052:web:f764bc97b5c631d84fddd1',
    messagingSenderId: '1000499954052',
    projectId: 'studentsjob-d9128',
    authDomain: 'studentsjob-d9128.firebaseapp.com',
    storageBucket: 'studentsjob-d9128.firebasestorage.app',
  );
}
